/* Clear initial data (if you so desire) 
DELETE FROM websites
DELETE FROM pages
DELETE FROM users
DELETE FROM themes
DELETE FROM websitedomains
DELETE FROM components
*/

/* Only Add initial data once */
IF (SELECT COUNT(*) FROM Users WHERE userId=1) = 0 BEGIN

	/* Setup Variable */
	DECLARE 
	@websiteTitle nvarchar(100) = 'Rennder',
	@pageDescription nvarchar(MAX) = 'Welcome to your new website, generated by the Rennder platform.'

	/* Create Default Administration Account */
	INSERT INTO Users 
	(userId, firstname, lastname, email, [password], displayname, photo, gender, bday, zipcode, city, 
	[state], country, twitter, lastlogin, datecreated, [status], signupip, referrer, [activation], deleted, tutorial) 
	VALUES 
	(1,'','','admin@localhost','EE44732CF1DEA4F780AF96C7F81BC11E','admin','',0,GETDATE(),'89103','Las Vegas',
	'NV','US','', GETDATE(), GETDATE(), 1, '', '', '', 0, 0)


	/* Setup Default Website Theme */
	INSERT INTO Themes
	(themeId, userId, designId, schemeId, websiteId, title, name, price, rating, ratingcount, ratingtotal, datecreated,
	approved, [private], [enabled], deleted, license, licensetype, [description])
	VALUES
	(1, 1, 0, 0, null, 'Default', 'default', 0, 0, 0, 0, GETDATE(), 
	1, 0, 1, 0, 0, 0, 'The default theme that comes with the Rennder platform')

	/* Create Default Website */
	INSERT INTO WebSites
	(websiteId, ownerId, themeId, designId, schemeId, title, icon, pagetemplate, pagehome, pagelogin, pageabout, 
	pagecontact, pagesupport, page404, pagedenied, datecreated, websitetype, license, licensetype, price, [enabled], 
	deleted, statustype, background)
	VALUES
	(1, 1, 1, null, null, @websiteTitle, 1, null, 1, 2, 3, 
	4, null, 5, 6, GETDATE(), 1, 0, 0, 0, 1,
	0, 1, '')

	/* Create Home Page */
	INSERT INTO Pages
	(pageId, ownerId, themeId, websiteId, parentId, schemeId, pagetype, title, [path], [pathIds], photo, datecreated,
	datemodified, datefirstpublished, datepublished, favorite, [security], usersonly, published, [enabled], deleted,
	rating, ratingtotal, ratedcount, background, [description])
	VALUES
	(1, 1, 1, 1, null, null, 1, @websiteTitle + ' - Home', '', '', '', GETDATE(),
	GETDATE(), GETDATE(), GETDATE(), 0, 0, 0, 1, 1, 0,
	0, 0, 0, '', @pageDescription)

	/* Create Login Page */
	INSERT INTO Pages
	(pageId, ownerId, themeId, websiteId, parentId, schemeId, pagetype, title, [path], [pathIds], photo, datecreated,
	datemodified, datefirstpublished, datepublished, favorite, [security], usersonly, published, [enabled], deleted,
	rating, ratingtotal, ratedcount, background, [description])
	VALUES
	(2, 1, 1, 1, null, null, 1, @websiteTitle + ' - Login', '', '', '', GETDATE(),
	GETDATE(), GETDATE(), GETDATE(), 0, 0, 0, 1, 1, 0,
	0, 0, 0, '', @pageDescription)

	/* Create About Page */
	INSERT INTO Pages
	(pageId, ownerId, themeId, websiteId, parentId, schemeId, pagetype, title, [path], [pathIds], photo, datecreated,
	datemodified, datefirstpublished, datepublished, favorite, [security], usersonly, published, [enabled], deleted,
	rating, ratingtotal, ratedcount, background, [description])
	VALUES
	(3, 1, 1, 1, null, null, 1, @websiteTitle + ' - About', '', '', '', GETDATE(),
	GETDATE(), GETDATE(), GETDATE(), 0, 0, 0, 1, 1, 0,
	0, 0, 0, '', @pageDescription)

	/* Create Contact Page */
	INSERT INTO Pages
	(pageId, ownerId, themeId, websiteId, parentId, schemeId, pagetype, title, [path], [pathIds], photo, datecreated,
	datemodified, datefirstpublished, datepublished, favorite, [security], usersonly, published, [enabled], deleted,
	rating, ratingtotal, ratedcount, background, [description])
	VALUES
	(4, 1, 1, 1, null, null, 1, @websiteTitle + ' - Contact', '', '', '', GETDATE(),
	GETDATE(), GETDATE(), GETDATE(), 0, 0, 0, 1, 1, 0,
	0, 0, 0, '', @pageDescription)

	/* Create 404 Page */
	INSERT INTO Pages
	(pageId, ownerId, themeId, websiteId, parentId, schemeId, pagetype, title, [path], [pathIds], photo, datecreated,
	datemodified, datefirstpublished, datepublished, favorite, [security], usersonly, published, [enabled], deleted,
	rating, ratingtotal, ratedcount, background, [description])
	VALUES
	(5, 1, 1, 1, null, null, 1, @websiteTitle + ' - Error 404', '', '', '', GETDATE(),
	GETDATE(), GETDATE(), GETDATE(), 0, 0, 0, 1, 1, 0,
	0, 0, 0, '', @pageDescription)

	/* Create Access Denied Page */
	INSERT INTO Pages
	(pageId, ownerId, themeId, websiteId, parentId, schemeId, pagetype, title, [path], [pathIds], photo, datecreated,
	datemodified, datefirstpublished, datepublished, favorite, [security], usersonly, published, [enabled], deleted,
	rating, ratingtotal, ratedcount, background, [description])
	VALUES
	(6, 1, 1, 1, null, null, 1, @websiteTitle + ' - Access Denied', '', '', '', GETDATE(),
	GETDATE(), GETDATE(), GETDATE(), 0, 0, 0, 1, 1, 0,
	0, 0, 0, '', @pageDescription)

	/* Create Default Domain */
	INSERT INTO WebsiteDomains
	(websiteId, domain, datecreated, googletoken, googleprofileId, googlewebpropertyId)
	VALUES(1, 'rennder.com', GETDATE(), '', '', '')

	/* Setup Available Components */
	INSERT INTO components (componentId, userId, title, category, [description], datecreated, orderindex)
	VALUES ('textbox', 1, 'Text', 1, 'Write formatted text directly onto your web page.', GETDATE(), 1)

	INSERT INTO components (componentId, userId, title, category, [description], datecreated, orderindex)
	VALUES ('panel', 1, 'Panel', 1, 'Drag & drop component into one or more panel cells or slideshow slides.', GETDATE(), 2)

	INSERT INTO components (componentId, userId, title, category, [description], datecreated, orderindex)
	VALUES ('photo', 1, 'Photo', 1, 'Upload an image from your computer to display and resize on the page', GETDATE(), 3)

	INSERT INTO components (componentId, userId, title, category, [description], datecreated, orderindex)
	VALUES ('photogallery', 1, 'Photo Gallery', 1, 'Display a list of photos in a grid or slideshow.', GETDATE(), 4)

	INSERT INTO components (componentId, userId, title, category, [description], datecreated, orderindex)
	VALUES ('video', 1, 'Video Player', 1, 'Display a video from YouTube or Vimeo.', GETDATE(), 5)

	INSERT INTO components (componentId, userId, title, category, [description], datecreated, orderindex)
	VALUES ('music', 1, 'Music Player', 1, 'Load a playlist from SoundCloud.', GETDATE(), 6)

	INSERT INTO components (componentId, userId, title, category, [description], datecreated, orderindex)
	VALUES ('menu', 1, 'Menu', 1, 'Create a navigation menu with links to other web pages.', GETDATE(), 7)

	INSERT INTO components (componentId, userId, title, category, [description], datecreated, orderindex)
	VALUES ('list', 1, 'List', 1, 'Create a customized list of information using text, photos, buttons, and HTML.', GETDATE(), 8)

	INSERT INTO components (componentId, userId, title, category, [description], datecreated, orderindex)
	VALUES ('button', 1, 'Button', 1, 'Add a button to your web page.', GETDATE(), 9)

	INSERT INTO components (componentId, userId, title, category, [description], datecreated, orderindex)
	VALUES ('page-title', 1, 'Page Title', 2, 'Display the title & description for your web pages instead of manually writing text on each page.', GETDATE(), 1)

	INSERT INTO components (componentId, userId, title, category, [description], datecreated, orderindex)
	VALUES ('page-list', 1, 'Page List', 2, 'Display a list of relevant web pages.', GETDATE(), 2)

	INSERT INTO components (componentId, userId, title, category, [description], datecreated, orderindex)
	VALUES ('page-comments', 1, 'Comments', 2, 'Give visitors a way to leave feedback on your page with Disqus or Facebook comments.', GETDATE(), 3)

	INSERT INTO components (componentId, userId, title, category, [description], datecreated, orderindex)
	VALUES ('page-maps', 1, 'Maps', 2, 'Add a Google map to provide a location to your business or venue.', GETDATE(), 4)

	INSERT INTO components (componentId, userId, title, category, [description], datecreated, orderindex)
	VALUES ('payments', 1, 'Payments', 2, 'Add a buy button from Paypal or Stripe onto your web page.', GETDATE(), 5)

END